    int game;
    int gamemode;
    int paddle;    
    int direction;
     
    int SHOW_IP_ON_BOOT;
    int AUTO_BRIGHTNESS;
    int BRIGHTNESS;
    int SHOW_WEEKDAY;
    int UTC_OFFSET;
    int BIG_TIME;
    int PET_MOOD;
    int AUTO_UPDATE;
    char TEXT_COLOR_R;
    char TEXT_COLOR_G;
    char TEXT_COLOR_B;
    int RAINBOW;
    int SCROLL_SPEED;
    int SOUND;
    int MATRIX_MODE;

    int PONG_ACTIVE;
    int SNAKE_ACTIVE;
    int TIME_ACTIVE;
    int ALEXA_ACTIVE;
    int WEATHER_ACTIVE;
    int WEATHERHUM_ACTIVE;
    int PET_ACTIVE;
    int GOL_ACTIVE;
    int DHT_ACTIVE;
    int YT_ACTIVE;
    int FB_ACTIVE;
    int TWITTER_ACTIVE;
    int FIRE_ACTIVE;
    int MQTT_ACTIVE;
    int BLYNK_ACTIVE;
    int SETTINGS_FOUND=0;
    int APP_DURATION=20;


    int SLEEP_START_MIN;
    int SLEEP_START_HR;
    int SLEEP_STOP_MIN;
    int SLEEP_STOP_HR;
    int SLEEP_MODE=0;
    int SLEEP_MODE_ACTIVE;

    char* OWM_API_KEY;
    char* OWM_LOCATION;
    char* YT_API_KEY;
    char* YT_CHANNEL_ID;
    char* FB_API_URL;
    char* TWITTER_PROFILE;
    char* FINGERPRINT;
    char* MQTT_SERVER;
    int MQTT_PORT;
    char* MQTT_USERNAME;
    char* MQTT_PASSWORD;
    char* BLYNK_KEY; 
